### ISSUE TITLE
No such module 'Sequence' in Playground

### ISSUE THREAD

**Issue by gmcusaro** [cgoldsby/Sequences#2]
Where can I find `import Sequences` in the Source and Playground? In Xcode it is *No such module 'Sequences'*

**Comment by cgoldsby** [comment]
Hi @giovannimariacusaro, I was able to get the playground to work after enabling "Build Active Scheme" in the Info panel. Hope this helps. Have a great day. 🌞 

<img width="1464" alt="Screen Shot 2021-05-03 at 5 06 15 PM" src="https://user-images.githubusercontent.com/3449816/116933782-078dae00-ac32-11eb-8374-d034dbc36518.png">

**Comment by gmcusaro** [comment]
Hi @cgoldsby thanks for reply. It works, but honestly I don't understand the need to create an xcworkspace for an example. To learn new things it certainly doesn't help. 😉
